/* Brand Constants — Studio Subhra */

export const BRAND = {
  name: 'Studio Subhra',
  tagline: 'Set the Trend',
  quote: "I don't sell products. I sell my dreams.",
  founder: 'Subhra Saha',
  founderQuote:
    'Innovation inspires me. I always look for originality and try to push boundaries with new techniques, blending fashion with comfort. Fashion is intellectual passion to me.',
  website: 'www.studiosubhra.in',
};

export const CONTACT = {
  email: 'subhraonly@yahoo.co.in',
  phone: '+91 99030 24696',
  whatsapp: '+91 98756 29283',
  location: 'Studio Subhra, Salt Lake, Kolkata',
  social: {
    facebook: 'https://www.facebook.com/subhracoutureofficial',
    instagram: 'https://instagram.com/studiosubhra',
    youtube: 'https://www.youtube.com/@subhra_saha',
    pinterest: 'https://in.pinterest.com/subhra_saha/',
  },
};

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Collections', path: '/collections' },
  { label: 'Ready to Wear', path: '/ready-to-wear' },
  { label: 'About', path: '/about' },
  { label: 'Lookbook', path: '/lookbook' },
  { label: 'Contact', path: '/contact' },
];

export const HERO_SLIDES = [
  {
    image: '/images/hero/slider0.jpg',
    title: 'Wear the Next You',
    subtitle: 'Futuristic Designs. Timeless Soul.',
    cta: 'Explore Collection',
  },
  {
    image: '/images/hero/slider1.jpg',
    title: 'Origami & Nature',
    subtitle: 'Where sculptural folds meet the beauty of nature.',
    cta: 'Discover',
  },
  {
    image: '/images/hero/slider2.jpg',
    title: 'Denim with a Soul',
    subtitle: 'Timeless tradition meets the bold spirit of denim.',
    cta: 'View Collection',
  },
  {
    image: '/images/hero/slider3.jpg',
    title: 'Wear Your Own Trend',
    subtitle: 'Contemporary designs for the modern you.',
    cta: 'Explore',
  },
];

export const COLLECTIONS = [
  {
    id: 'denim',
    title: 'Denim Saree',
    subtitle: 'Desi Heritage. Global Attitude.',
    description:
      'A Global-Desi expression of the saree, where timeless tradition meets the bold spirit of denim. Studio Subhra reimagines the saree for the modern woman by blending traditional draping with contemporary denim, statement details and a touch of street-style attitude.',
    tagline: 'Desi Heritage. Global Attitude.',
    images: [
      '/images/denim/denim1.jpg',
      '/images/denim/denim2.jpg',
      '/images/denim/denim3.jpg',
      '/images/denim/denim4.jpg',
      '/images/denim/denim5.jpg',
      '/images/denim/denim6.jpg',
      '/images/denim/denim7.jpg',
      '/images/denim/denim8.jpg',
      '/images/denim/denim9.jpg',
    ],
    color: '#1E3A5F',
  },
  {
    id: 'origami',
    title: 'Inspiration Origami',
    subtitle: 'Nature × Origami × Fashion',
    description:
      'Inspired by the delicate art of Origami and the organic beauty of Nature, this collection explores the harmony between sculptural folds, flowing drapes, natural textures, and graceful silhouettes.',
    tagline: 'Nature × Origami × Fashion',
    images: [
      '/images/dreams/dreams1.jpg',
      '/images/dreams/dreams2.jpg',
      '/images/dreams/dreams3.jpg',
      '/images/dreams/dreams4.jpg',
      '/images/dreams/dreams5.jpg',
    ],
    color: '#5B8C5A',
  },
  {
    id: 'pret',
    title: 'Designer Prêt',
    subtitle: 'Contemporary Luxury & Everyday Elegance',
    description:
      'A refined dialogue between haute craftsmanship and effortless wearable luxury. Studio Subhra Designer Prêt brings structured tailoring, fluid drapery, and elevated contemporary aesthetics into your everyday wardrobe.',
    tagline: 'Modern Elegance.',
    images: [
      '/images/designer-pret/pret1.jpg',
      '/images/designer-pret/pret2.jpg',
      '/images/designer-pret/pret3.jpg',
      '/images/designer-pret/pret4.jpg',
      '/images/designer-pret/pret5.jpg',
      '/images/designer-pret/pret6.jpg',
      '/images/designer-pret/pret7.jpg',
      '/images/designer-pret/pret8.jpg',
      '/images/designer-pret/pret9.jpg',
      '/images/designer-pret/pret10.jpg',
      '/images/designer-pret/pret11.jpg',
      '/images/designer-pret/pret12.jpg',
      '/images/designer-pret/pret13.jpg',
      '/images/designer-pret/pret14.jpg',
      '/images/designer-pret/pret15.jpg',
      '/images/designer-pret/pret16.jpg',
    ],
    color: '#C4956A',
  },
  {
    id: 'knit',
    title: 'Knit Concept Saree',
    subtitle: 'A New Discovery in Fashion',
    description:
      'Redefining elegance through the art of draping. A patterned saree crafted with soft, flexible knit fabric — blending traditional drapes with modern comfort and texture.',
    tagline: 'Traditional Roots. Modern Twist.',
    images: [
      '/images/knit/knit1.jpg',
      '/images/knit/knit2.jpg',
      '/images/knit/knit3.jpg',
      '/images/knit/knit4.jpg',
    ],
    color: '#9B6B9E',
  },
  {
    id: 'arriving',
    title: 'Arriving Soon',
    subtitle: '',
    description:
      'Exclusive previews of the upcoming Studio Subhra campaign. Modern silhouettes, bold architectural drapes, and avant-garde craftsmanship set to define the season ahead.',
    tagline: 'Set The Trend — Coming Soon',
    images: [
      '/images/arriving-soon/arriving1.jpg',
      '/images/arriving-soon/arriving2.jpg',
    ],
    color: '#2A2A2A',
  },
];

export const BRAND_VALUES = [
  {
    icon: 'Leaf',
    title: 'Premium Fabrics',
    description: 'Handpicked materials that feel as luxurious as they look.',
  },
  {
    icon: 'Gem',
    title: 'Trendy Designs',
    description: 'Where heritage craft meets contemporary global style.',
  },
  {
    icon: 'Heart',
    title: 'Made with Love',
    description: 'Every stitch carries passion, every fold tells a story.',
  },
];

export const READY_TO_WEAR_ITEMS = [
  {
    id: 'rtw-1',
    image: '/images/ready-to-wear/rtw1.jpg',
    title: 'Prêt Silhouette I',
    subtitle: 'Contemporary Draped Ensemble',
    category: 'Ready to Wear',
    badge: 'Prêt-à-Porter',
    price: 'Price on Request',
  },
  {
    id: 'rtw-2',
    image: '/images/ready-to-wear/rtw2.jpg',
    title: 'Sculptural Pleated Co-Ord',
    subtitle: 'Signature Architectural Silhouette',
    category: 'Ready to Wear',
    badge: 'Trending',
    price: 'Price on Request',
  },
  {
    id: 'rtw-3',
    image: '/images/ready-to-wear/rtw3.jpg',
    title: 'Avant-Garde Drape Set',
    subtitle: 'Artisanal Modern Drape',
    category: 'Ready to Wear',
    badge: 'Signature',
    price: 'Price on Request',
  },
  {
    id: 'rtw-4',
    image: '/images/ready-to-wear/rtw4.jpg',
    title: 'Modern Heritage Drape',
    subtitle: 'High-Fashion Fusion Look',
    category: 'Ready to Wear',
    badge: 'New Arrival',
    price: 'Price on Request',
  },
  {
    id: 'rtw-5',
    image: '/images/ready-to-wear/rtw5.jpg',
    title: 'Luxe Origami Pleat Ensemble',
    subtitle: 'Sculpted Silhouette & Flowing Lines',
    category: 'Ready to Wear',
    badge: 'Prêt-à-Porter',
    price: 'Price on Request',
  },
  {
    id: 'rtw-6',
    image: '/images/ready-to-wear/rtw6.jpg',
    title: 'Contemporary Layered Silhouette',
    subtitle: 'Elegance in Motion',
    category: 'Ready to Wear',
    badge: 'Exclusive',
    price: 'Price on Request',
  },
  {
    id: 'rtw-7',
    image: '/images/ready-to-wear/rtw7.jpg',
    title: 'Botanical Sculptural Ensemble',
    subtitle: 'Organic Forms & Precision Draping',
    category: 'Ready to Wear',
    badge: 'Haute Prêt',
    price: 'Price on Request',
  },
  {
    id: 'rtw-8',
    image: '/images/ready-to-wear/rtw8.jpg',
    title: 'Urban Fusion Statement Look',
    subtitle: 'Sophisticated Street Couture',
    category: 'Ready to Wear',
    badge: 'Bestseller',
    price: 'Price on Request',
  },
  {
    id: 'rtw-9',
    image: '/images/ready-to-wear/rtw9.jpg',
    title: 'Artisanal Pleated Tunic Set',
    subtitle: 'Fluid Architectural Cut',
    category: 'Ready to Wear',
    badge: 'Atelier',
    price: 'Price on Request',
  },
  {
    id: 'rtw-10',
    image: '/images/ready-to-wear/rtw10.jpg',
    title: 'Monochromatic Draped Creation',
    subtitle: 'Timeless Silhouette with Modern Attitude',
    category: 'Ready to Wear',
    badge: 'Prêt-à-Porter',
    price: 'Price on Request',
  },
  {
    id: 'rtw-11',
    image: '/images/ready-to-wear/rtw11.jpg',
    title: 'Structured Origami Top & Drape',
    subtitle: 'Crisp Folds & Flawless Tailoring',
    category: 'Ready to Wear',
    badge: 'Trending',
    price: 'Price on Request',
  },
  {
    id: 'rtw-12',
    image: '/images/ready-to-wear/rtw12.jpg',
    title: 'Ethereal Pleated Gown Concept',
    subtitle: 'Graceful Drapery & Fluid Elegance',
    category: 'Ready to Wear',
    badge: 'Signature',
    price: 'Price on Request',
  },
  {
    id: 'rtw-13',
    image: '/images/ready-to-wear/rtw13.jpg',
    title: 'Asymmetric Modern Saree Look',
    subtitle: 'Subtle Sheen & Bold Geometry',
    category: 'Ready to Wear',
    badge: 'New Arrival',
    price: 'Price on Request',
  },
  {
    id: 'rtw-14',
    image: '/images/ready-to-wear/rtw14.jpg',
    title: 'Contemporary Festive Prêt',
    subtitle: 'Sculpted Elegance for Occasions',
    category: 'Ready to Wear',
    badge: 'Exclusive',
    price: 'Price on Request',
  },
  {
    id: 'rtw-15',
    image: '/images/ready-to-wear/rtw15.jpg',
    title: 'Minimalist Pleated Cape Set',
    subtitle: 'Clean Aesthetic & High Impact',
    category: 'Ready to Wear',
    badge: 'Haute Prêt',
    price: 'Price on Request',
  },
  {
    id: 'rtw-16',
    image: '/images/ready-to-wear/rtw16.jpg',
    title: 'Runway Statement Silhouette',
    subtitle: 'Bold Architecture Meets Comfort',
    category: 'Ready to Wear',
    badge: 'Runway Edition',
    price: 'Price on Request',
  },
  {
    id: 'rtw-17',
    image: '/images/ready-to-wear/rtw17.jpg',
    title: 'Sculptural Collar Fusion Dress',
    subtitle: 'Modern Draping with Heritage Spirit',
    category: 'Ready to Wear',
    badge: 'Atelier',
    price: 'Price on Request',
  },
  {
    id: 'rtw-18',
    image: '/images/ready-to-wear/rtw18.jpg',
    title: 'Geometric Pleated Ensemble',
    subtitle: 'Dynamic Lines & Fluid Movement',
    category: 'Ready to Wear',
    badge: 'Prêt-à-Porter',
    price: 'Price on Request',
  },
  {
    id: 'rtw-19',
    image: '/images/ready-to-wear/rtw19.jpg',
    title: 'Signature Drape Concept 19',
    subtitle: 'Exquisite Craftsmanship & Style',
    category: 'Ready to Wear',
    badge: 'Trending',
    price: 'Price on Request',
  },
  {
    id: 'rtw-20',
    image: '/images/ready-to-wear/rtw20.jpg',
    title: 'Chic Urban Drape Silhouette',
    subtitle: 'Effortless Contemporary Luxury',
    category: 'Ready to Wear',
    badge: 'Exclusive',
    price: 'Price on Request',
  },
  {
    id: 'rtw-21',
    image: '/images/ready-to-wear/rtw21.jpg',
    title: 'Avant-Garde Pleated Cape Dress',
    subtitle: 'Sculpted Volume & Precision',
    category: 'Ready to Wear',
    badge: 'Signature',
    price: 'Price on Request',
  },
  {
    id: 'rtw-22',
    image: '/images/ready-to-wear/rtw22.jpg',
    title: 'High-Fashion Fusion Co-Ord',
    subtitle: 'Contemporary Redefinition of Craft',
    category: 'Ready to Wear',
    badge: 'Haute Prêt',
    price: 'Price on Request',
  },
  {
    id: 'rtw-23',
    image: '/images/ready-to-wear/rtw23.jpg',
    title: 'Atelier Signature Drape 23',
    subtitle: 'Graceful Flow & Structured Forms',
    category: 'Ready to Wear',
    badge: 'Atelier',
    price: 'Price on Request',
  },
  {
    id: 'rtw-24',
    image: '/images/ready-to-wear/rtw24.jpg',
    title: 'Couture Prêt Finale Look',
    subtitle: 'The Pinnacle of Studio Subhra Prêt',
    category: 'Ready to Wear',
    badge: 'Runway Edition',
    price: 'Price on Request',
  },
];

